INTROSPECTION_KEYMAP_C += triplem.c

GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = no

# Reduce compiled size
VIA_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no
